// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAskOqjryToxihQGVelQwGrUWXbiHk6zkw',
    appId: '1:286010032006:web:17ce8e9e659526f371f607',
    messagingSenderId: '286010032006',
    projectId: 'quiztime-d4aff',
    authDomain: 'quiztime-d4aff.firebaseapp.com',
    storageBucket: 'quiztime-d4aff.firebasestorage.app',
    measurementId: 'G-M887P3TZ26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDez799XOs9OkpKsOCh8VE_xKmGXnMBReQ',
    appId: '1:286010032006:android:5ce17f0068fe969f71f607',
    messagingSenderId: '286010032006',
    projectId: 'quiztime-d4aff',
    storageBucket: 'quiztime-d4aff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-dNXlDjRWOxzy7jCridgq9KQv_w9S0Zo',
    appId: '1:286010032006:ios:906f901d4e88c71e71f607',
    messagingSenderId: '286010032006',
    projectId: 'quiztime-d4aff',
    storageBucket: 'quiztime-d4aff.firebasestorage.app',
    iosBundleId: 'com.example.quiztime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-dNXlDjRWOxzy7jCridgq9KQv_w9S0Zo',
    appId: '1:286010032006:ios:906f901d4e88c71e71f607',
    messagingSenderId: '286010032006',
    projectId: 'quiztime-d4aff',
    storageBucket: 'quiztime-d4aff.firebasestorage.app',
    iosBundleId: 'com.example.quiztime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAskOqjryToxihQGVelQwGrUWXbiHk6zkw',
    appId: '1:286010032006:web:38312bdeb04ea4be71f607',
    messagingSenderId: '286010032006',
    projectId: 'quiztime-d4aff',
    authDomain: 'quiztime-d4aff.firebaseapp.com',
    storageBucket: 'quiztime-d4aff.firebasestorage.app',
    measurementId: 'G-2EK3Y04WP1',
  );
}
